### ISSUE TITLE
Failed to generate ChemGPT embedding from large files.

### ISSUE THREAD

**Issue by peiyaoli** [datamol-io/molfeat#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

I tried to generate the ChemGPT embedding from SMILES.

The official document's demo works fine.
But when I tried to run with 17k SMILES, the error comes out.
Should I split whole file into small chunks and call the API?
```
Traceback (most recent call last):
  File "/home/peiyaoli/Projects/****/generate_molecular_features.py", line 156, in <module>
    main()
  File "/home/peiyaoli/Projects/****/generate_molecular_features.py", line 142, in main
    chemgpt1B_feats = generate_chemgpt_1B_embeddings(df)
  File "/home/peiyaoli/Projects/****/generate_molecular_features.py", line 32, in generate_chemgpt_1B_embeddings
    embeddings = transformer(df.SMILES)
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/molfeat/trans/base.py", line 377, in __call__
    features = self.transform(mols, ignore_errors=ignore_errors, enforce_dtype=False, **kwargs)
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/molfeat/trans/pretrained/base.py", line 208, in transform
    converted_mols = self._convert(mols, **kwargs)
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/molfeat/trans/pretrained/hf_transformers.py", line 375, in _convert
    encoded = self.featurizer.tokenizer(
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2538, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2624, in _call_one
    return self.batch_encode_plus(
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2815, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/peiyaoli/miniconda3/envs/molsai/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 428, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

**Comment by peiyaoli** [comment]
I found that some smiles failed to be encoded as SELFIES, that is why it fails. So

**Comment by maclandrol** [comment]
Thanks @peiyaoli, Don't hesitate to make a PR to improve the error message. 

We have an `ignore_errors` argument, that should normally ignore the failing featurization and return the index of the successful ones, it can surely be improved for pretrained models.
