### ISSUE TITLE
Error Handling for Dataframes as input for MolecularTransformer

### ISSUE THREAD

**Issue by thibaultvarin-r** [datamol-io/molfeat#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

Error when mols passed to a MoleculeTransformer are in a DataFrame.

from molfeat.trans.base import MoleculeTransformer
import pandas as pd
df = pd.DataFrame({'smiles', ['c1ccccc1', 'c1ccccc1CO']})
transformer_ecfp = MoleculeTransformer(featurizer='ecfp')
results = transformer_ecfp.fit_transform(df[['smiles']])

It is an issue also when working with a ColumnTransformer to pass the smiles column to transformer_ecfp in a pipeline.

[11:01:30] SMILES Parse Error: syntax error while parsing: smiles
[11:01:30] SMILES Parse Error: Failed parsing SMILES 'smiles' for input: 'smiles'
[11:01:30] SMILES Parse Error: syntax error while parsing: smiles
[11:01:30] SMILES Parse Error: Failed parsing SMILES 'smiles' for input: 'smiles'
Traceback (most recent call last):
  File "/mnt/ps/home/CORP/thibault.varin/.config/JetBrains/RemoteDev-PY/_mnt_ps_home_CORP_thibault.varin_PycharmProjects_molfeat/scratches/scratch.py", line 6, in <module>
    results = transformer_ecfp.fit_transform(df[['smiles']])
  File "/mnt/ps/home/CORP/thibault.varin/.virtualenvs/molfeat/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/mnt/ps/home/CORP/thibault.varin/.virtualenvs/molfeat/lib/python3.8/site-packages/sklearn/base.py", line 915, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/mnt/ps/home/CORP/thibault.varin/.virtualenvs/molfeat/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/mnt/ps/home/CORP/thibault.varin/PycharmProjects/molfeat/molfeat/trans/base.py", line 328, in transform
    raise ValueError(
ValueError: Cannot transform molecule at index 0. Please check logs (set verbose to True) to see errors!

### How to reproduce the bug

```python
from molfeat.trans.base import MoleculeTransformer
import pandas as pd
df = pd.DataFrame({'smiles', ['c1ccccc1', 'c1ccccc1CO']})
transformer_ecfp = MoleculeTransformer(featurizer='ecfp')
results = transformer_ecfp.fit_transform(df[['smiles']])
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

**Comment by thibaultvarin-r** [comment]
It was also discussed with @maclandrol.
I created a PR https://github.com/datamol-io/molfeat/pull/77
